version: "3"

services:
  app:
    image: node:14-alpine
    command: /bin/sh -c "
      cd /usr/src/app &&
      yarn install &&
      yarn run start:dev"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:4
    ports:
      - 27017:27017
    volumes:
      - /data/db
    logging:
      driver: none
